spring:
  profiles:
    active: dev

--- 
server:
  port: 8201



spring:
  profile: dev
  applicaiton:
    name: test-cloud-dev-1.0



---

# spring:
#   profile: test
#   applicaiton:
#     name: test-cloud-dev-2.0      
